### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by cristea2017** [NeRo8/rn-start-js#1]
Nice ideia , can you integrate autamatic install of library such as :

navigation , redux and so on .

I made a bash script for this , you can see below. it will be great to have such feature ;)

```bash 
install_Navigation(){
    npm i react-native-gesture-handler react-native-reanimated react-navigation react-native-screens react-navigation-stack react-navigation-tabs 
    echo "Navigation Instaled"
    
}

install_Redux(){
    npm i react-redux redux redux-persist --save-dev redux-devtools
    echo " Redux Installed"
}

read -r -p 'Project Name >>> : ' reacNativeName
read -r -p 'Do You Need Navigation ? >>> (y/n)): ' reactNavigation
read -r -p 'Do You Need Redux ? >>> (y/n): ' reactRedux

echo '##############Project Will Be Saved To Desktop !!!##############'
cd Desktop
npx react-native init "$reacNativeName"
cd "$reacNativeName"
if [ "$reactNavigation" == 'y' ]; then
    echo "Installing Navigation !"
    install_Navigation;
fi

if [ "$reactRedux" == 'y' ]; then
    echo "Installing Redux!"
    install_Redux;
fi

# Install Pods !important
cd ios 
pod install
cd ..


echo "$reacNativeName Created, configured and cleared"
  
 ```

**Comment by NeRo8** [comment]
Hello, thank you for your help. But I already wrote the script on my own.

`import chalk from "chalk";

const packageList = [
  "redux",
  "react-redux",
  "axios",
  "i18n-js",
  "lodash.memoize",
  "react-native-extended-stylesheet",
  "react-native-gesture-handler",
  "react-native-reanimated",
  "react-native-safe-area-context",
  "react-native-screens",
  "react-native-svg",
  "react-native-svg-transformer",
  "@react-native-community/masked-view",
  "@react-navigation/native",
  "@react-navigation/stack",
];

const tsPackageList = [
  "typescript",
  "@types/jest",
  "@types/react",
  "@types/react-native",
  "@types/react-test-renderer",
];

function execShellCommand(cmd) {
  const exec = require("child_process").exec;

  console.log(
    chalk.yellow(`Dependencies ${cmd} installation process has started`)
  );
  exec(`npm install --save ${cmd}`, (error, stdout, stderr) => {
    if (error) {
      console.log(chalk.red("Error:", error));
    }

    stdout
      ? console.log(chalk.green(`Success install package`, stdout))
      : console.log(chalk.green(`Error  install package`, stderr));
  });
}

function execShellCommandDev(cmd) {
  const exec = require("child_process").exec;

  console.log(
    chalk.yellow(`Dev Dependencies ${cmd} installation process has started`)
  );
  exec(`npm install --save-dev ${cmd}`, (error, stdout, stderr) => {
    if (error) {
      console.log(chalk.red("Error:", error));
    }

    stdout
      ? console.log(chalk.green(`Success install package`, stdout))
      : console.log(chalk.green(`Error  install package`, stderr));
  });
}

export function installAllTsPackage() {
  console.log(chalk.yellow("\nPlease wait, we install dependencies\n"));

  packageList.forEach((item) => {
    execShellCommand(item);
  });

  tsPackageList.forEach((item) => {
    execShellCommandDev(item);
  });
}

export default function installAllJsPackage() {
  console.log(chalk.yellow("\nPlease wait, we install dependencies\n"));

  packageList.forEach((item) => {
    execShellCommand(item);
  });
}
`

**Comment by NeRo8** [comment]
> Nice ideia , can you integrate autamatic install of library such as :
> 
> navigation , redux and so on .
> 
> I made a bash script for this , you can see below. it will be great to have such feature ;)
> 
> ```shell
> install_Navigation(){
>     npm i react-native-gesture-handler react-native-reanimated react-navigation react-native-screens react-navigation-stack react-navigation-tabs 
>     echo "Navigation Instaled"
>     
> }
> 
> install_Redux(){
>     npm i react-redux redux redux-persist --save-dev redux-devtools
>     echo " Redux Installed"
> }
> 
> read -r -p 'Project Name >>> : ' reacNativeName
> read -r -p 'Do You Need Navigation ? >>> (y/n)): ' reactNavigation
> read -r -p 'Do You Need Redux ? >>> (y/n): ' reactRedux
> 
> echo '##############Project Will Be Saved To Desktop !!!##############'
> cd Desktop
> npx react-native init "$reacNativeName"
> cd "$reacNativeName"
> if [ "$reactNavigation" == 'y' ]; then
>     echo "Installing Navigation !"
>     install_Navigation;
> fi
> 
> if [ "$reactRedux" == 'y' ]; then
>     echo "Installing Redux!"
>     install_Redux;
> fi
> 
> # Install Pods !important
> cd ios 
> pod install
> cd ..
> 
> 
> echo "$reacNativeName Created, configured and cleared"
>   
> ```


Hi, at the moment there is an auto-installation of dependencies, but it sometimes does not work correctly. 
Thank you for your help.
```
import installAllJsPackage, {
  installAllTsPackage,
} from "./utils/installPackage";

var path = require("path");
var fs = require("fs-extra");

var sourceJS = path.join(__dirname, "/static/js");

var sourceTS = path.join(__dirname, "/static/ts");
var sourceTsConfigFiles = path.join(__dirname, "static/configFiles");

var destination = process.cwd() + "/src";
var destinationTsConfig = process.cwd();

function installJs() {
  fs.copy(sourceJS, destination, function (err) {
    if (err) {
      console.log("An error occured while copying the folder.");
      return console.error(err);
    }
  });

  installAllJsPackage();
}

function installTs() {
  fs.copy(sourceTS, destination, function (err) {
    if (err) {
      console.log("An error occured while copying the folder.");
      return console.error(err);
    }
  });

  fs.copy(sourceTsConfigFiles, destinationTsConfig, function (err) {
    if (err) {
      console.log("An error occured while copying the folder.");
      return console.error(err);
    }
  });

  installAllTsPackage();
}

export function cli(args) {
  if (args[2] === "ts") {
    installTs();
  } else {
    installJs();
  }
}
```

**Comment by NeRo8** [comment]
I fix this problem. Thanks @cristea2017 i find solution, take your idea and change some part of my script.
